# Generated by Django 4.2.16 on 2024-11-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base_user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="user", old_name="user_id", new_name="id",),
    ]
